name: Linux
on:
   push:
     branches: [ "master", "develop" ]
   pull_request:
     branches: [ "develop" ]
permissions:
   contents: read
   actions: read
   packages: read

jobs:
  compile-basic-features:
    runs-on: ${{ matrix.os }}
    name: compile basic_features '${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-22.04, ubuntu-26.04]
        #os: [ubuntu-26.04]
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/basic_features/build" >> "$GITHUB_OUTPUT"
    - name: Dependencies
      run: >
          sudo apt-get update && sudo apt-get -y install cmake libssl-dev zlib1g-dev libboost-dev libboost-test-dev
          libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-system-dev
          libboost-thread-dev libboost-date-time-dev
      # Install extra deps for ubuntu 26-04 (and add valgrind and coverage tests)
    - name: Extra Dependecies Ubuntu 26.04
      if: ${{ (matrix.os == 'ubuntu-26.04' || matrix.os == 'ubuntu-26.04-arm') }}
      run: >
        sudo apt-get install -y libjitterentropy3-dev valgrind lcov gcovr
    - name: Configure CMake
      # Configure the basic_features example in a 'build' subdirectory. 
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: >
        /usr/bin/cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=Debug
        -S ${{ github.workspace }}/basic_features
        -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.build-output-dir }}
        -DLCC_PROJECT_NAME=DEFAULT
    - name: Build
      # Build and install the example (also builds and installs licensecc from the submodule).
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: |
           /usr/bin/cmake --build ${{ steps.strings.outputs.build-output-dir }} -j $(nproc) --target install --config Debug
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest . --build-config Debug --output-on-failure
      env:
         CTEST_OUTPUT_ON_FAILURE: 1
         BOOST_TEST_LOG_LEVEL: message
    - name: Upload artifacts (Ubuntu 26.04)
      if: ${{ matrix.os == 'ubuntu-26.04' }}
      uses: actions/upload-artifact@v4
      with:
        retention-days: 3
        name: basic_features-ubuntu-26.04
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/bin/hardware_detection/hardware_detection
          ${{ steps.strings.outputs.build-output-dir }}/bin/program_features/program_features
          ${{ steps.strings.outputs.build-output-dir }}/bin/lccgen
          ${{ github.workspace }}/basic_features/projects/

  test-hardware-detection:
    needs: compile-basic-features
    runs-on: ubuntu-26.04
    name: Hardware Detection (generate-lic)
    steps:
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "extract-dir=${{ github.workspace }}/extract" >> "$GITHUB_OUTPUT"
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: basic_features-ubuntu-26.04
        path: ${{ steps.strings.outputs.extract-dir }}
    - name: List downloaded artifacts (verbose)
      run: find ${{ steps.strings.outputs.extract-dir }} -type f
    - name: Fix executable bit
      run: |
          chmod a+x ${{ steps.strings.outputs.extract-dir }}/build/bin/lccgen
          chmod a+x ${{ steps.strings.outputs.extract-dir }}/build/bin/hardware_detection/hardware_detection
          chmod a+x ${{ steps.strings.outputs.extract-dir }}/build/bin/program_features/program_features
    - name: Issue license for hardware_detection
      working-directory: ${{ steps.strings.outputs.extract-dir }}
      run: >
        ${{ steps.strings.outputs.extract-dir }}/build/bin/lccgen license issue
        -p ${{ steps.strings.outputs.extract-dir }}/projects/DEFAULT/
        -o ${{ steps.strings.outputs.extract-dir }}/build/bin/hardware_detection/hardware_detection.lic      
    - name: Run the executable
      working-directory: ${{ steps.strings.outputs.extract-dir }}
      run: >
        ${{ steps.strings.outputs.extract-dir }}/build/bin/hardware_detection/hardware_detection